spring.datasource.url=${IDENTITY_DB_URL:jdbc:postgresql://localhost:5432/dating_app}
spring.datasource.username=${IDENTITY_DB_USERNAME:dating_user}
spring.datasource.password=${IDENTITY_DB_PASSWORD:dating_password}

spring.jpa.show-sql=${IDENTITY_JPA_SHOW_SQL:true}
spring.jpa.properties.hibernate.format_sql=${IDENTITY_JPA_FORMAT_SQL:true}

identity.otp.delivery-provider=local
